title = "OneFrame"  # From Git
gitRepoUrl = "https://github.com/daulric/OneFrame" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "daulric"
projectName = "OneFrame"
url = "https://daulric.github.io"
baseUrl = "/OneFrame"
tagline = "Running a modular code under one server/client"

[home]
enabled = true
includeReadme = true # Optional

[footer]
style = "dark"
copyright = "Copyright © 2022 UA Software"

[navbar]

[[navbar.items]]
href = "https://discord.gg/jFZzfMFAts"
label = "Discord"
position = "right"

[[footer.links]]
title = "Contacts"

[[footer.links.items]]
label = "Twitter"
href = "https://twitter.com/daulricc"

[[footer.links.items]]
label = "YouTube"
href = "https://youtube.com/@daulric"