title = "OneFrame"  # From Git
gitRepoUrl = "https://github.com/daulric/OneFrame" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
url = "https://daulric.github.io"
baseUrl = "/OneFrame"
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "images/logo.png"

# From git:
organizationName = "daulric"
projectName = "OneFrame"
tagline = "Running a modular code under one server/client"

[home]
enabled = true
includeReadme = true

[[home.features]]
title = "Fast"
description = "Module run codes very quickly withput having to stop pause for any errors along the way."

[[home.features]]
title = "Reliable"
description = "OneFrame offers type support to make the code much easier to handle when developing your projects/games."

[[home.features]]
title = "Organized"
description = "Modules are much more organized in folders and avoid clustered scripts all over the game."

[footer]
style = "dark"
copyright = "Copyright © 2022 UA Software"

[navbar]

[[navbar.items]]
href = "https://discord.gg/jFZzfMFAts"
label = "Discord"
position = "right"

[[footer.links]]
title = "Contacts"

[[footer.links.items]]
label = "Twitter"
href = "https://twitter.com/daulricc"

[[footer.links.items]]
label = "YouTube"
href = "https://youtube.com/@daulric"