[package]
name = "daulric/oneframe"
description = "A module used to run folder or object with modular code in one single server or client"
version = "0.2.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]