[package]
name = "daulric/oneframe"
description = "A module used to run folders or objects with modular code inside one single server or client"
version = "0.3.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]